sudo: false
language: python
env:
  matrix:
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
   - DJANGO="Django<1.12"
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.11"
    - python: "3.6"
      env: DJANGO="Django<1.8"
    - python: "3.6"
      env: DJANGO="Django<1.9"
    - python: "3.6"
      env: DJANGO="Django<1.10"
install:
 - pip install "$DJANGO"
script:
 - python runtests.py
