language: python
env:
 - DJANGO_VERSION=1.6.11
 - DJANGO_VERSION=1.7.9
 - DJANGO_VERSION=1.8.3
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
install:
 - pip install -q Django==$DJANGO_VERSION
script:
 - python runtests.py
